### PR TITLE
Put multiple metric values

### PR DESCRIPTION
**Pull request by Hinidu**
Hello!
`PutMetricData` API allows to publish arrays of values and the number of times each value occurred during the period by using the `Values` and `Counts` fields in the `MetricDatum` structure.
But now they are not formatted properly:
```
      "MetricData.member.2.Counts.1" => 10,
      "MetricData.member.2.Counts.2" => 1,
      "MetricData.member.2.Counts.3" => 5,
      "MetricData.member.2.Counts.4" => 188,
      "MetricData.member.2.Values.1" => 1,
      "MetricData.member.2.Values.2" => 2,
      "MetricData.member.2.Values.3" => 3.5,
      "MetricData.member.2.Values.4" => 4.2,
```
Instead of:
```
      "MetricData.member.2.Counts.member.1" => 10,
      "MetricData.member.2.Counts.member.2" => 1,
      "MetricData.member.2.Counts.member.3" => 5,
      "MetricData.member.2.Counts.member.4" => 188,
      "MetricData.member.2.Values.member.1" => 1,
      "MetricData.member.2.Values.member.2" => 2,
      "MetricData.member.2.Values.member.3" => 3.5,
      "MetricData.member.2.Values.member.4" => 4.2,
```

### CODE REVIEW

**Comment by Hinidu** [comment]
@cammellos could you please review this PR?

**Comment by cammellos** [comment]
@Hinidu thanks for reminding me, I will do probably during in the weekend, not able to access my laptop as travelling!

**Comment by Hinidu** [comment]
Thanks @cammellos! Sorry for bothering you, have a good trip)

**Comment by Hinidu** [comment]
I just want to say that I already use this code in production for more than a month now and didn't see any issues yet. So I think it's quite safe to merge when you will get some time.

**Comment by cammellos** [comment]
@Hinidu thanks, I was hoping @benwilson512 would grant me access to the aws hex repo before mergin, https://github.com/ex-aws/ex_aws/issues/599 , but no luck so far, I will take some time today and merge, thanks for your patience!

**Review by cammellos — APPROVED** [review]

**Comment by Hinidu** [comment]
@cammellos thank you for the merge! I hope @benwilson512 will grant you access to hex repo soon.

**Comment by cammellos** [comment]
@Hinidu thanks for the contribution!

**Pull request merged**
