### PR TITLE
new pr for put_metric_data

### PR DESCRIPTION
**Pull request by danj3**
Same PR for put_metric_data against new repo.

### CODE REVIEW

**Comment by Trevoke** [comment]
Hello! We have a use for this feature and I would like to know if there's anything I can do to help get it merged.

**Comment by danj3** [comment]
Hi Ben, any chance of this merging?

**Comment by yumeto** [comment]
@danj3 , thanks to create the first impl of `put_metric_data`, that exactly what i want.
But #4 covers this PR so can you close this PR and proceed with #4?

**Comment by cammellos** [comment]
@danj3 Thanks for the contribution! closing this in favour of #4

**Pull request closed without merging**
